Repository Crio-Bytes/Miscellaneous, pull requests merged in 2020-10, with the labels that each got.

#1 [MicroByte] Building a Decoupled Voice Assistant
  Building_a_Decoupled_Voice_Assistant/README.md
  Building_a_Decoupled_Voice_Assistant/images/activity-1/activity-1a.jpg
  Building_a_Decoupled_Voice_Assistant/images/activity-1/activity-1b.jpg
  Building_a_Decoupled_Voice_Assistant/images/activity-2/activity-2a.jpg
  Building_a_Decoupled_Voice_Assistant/images/activity-2/activity-2b.gif
  Building_a_Decoupled_Voice_Assistant/images/activity-3/activity-3.gif
  Building_a_Decoupled_Voice_Assistant/images/activity-4/activity-4.gif
  Building_a_Decoupled_Voice_Assistant/images/activity-5/activity-5a.jpg
  Building_a_Decoupled_Voice_Assistant/images/activity-5/activity-5b.gif
  Building_a_Decoupled_Voice_Assistant/images/activity-5/activity-5c.gif
  Building_a_Decoupled_Voice_Assistant/images/netlify_cli_installation.jpg
  Building_a_Decoupled_Voice_Assistant/src/activity-1/activity-1a.html
  Building_a_Decoupled_Voice_Assistant/src/activity-1/activity-1a.js
  Building_a_Decoupled_Voice_Assistant/src/activity-1/activity-1b.html
  Building_a_Decoupled_Voice_Assistant/src/activity-1/activity-1b.js
  Building_a_Decoupled_Voice_Assistant/src/activity-1/activity-1c.html
  Building_a_Decoupled_Voice_Assistant/src/activity-1/activity-1c.js
  Building_a_Decoupled_Voice_Assistant/src/activity-2/functions/colour.js
  Building_a_Decoupled_Voice_Assistant/src/activity-2/functions/microbytes.js
  Building_a_Decoupled_Voice_Assistant/src/activity-2/netlify.toml
  Building_a_Decoupled_Voice_Assistant/src/activity-3/index.html
  Building_a_Decoupled_Voice_Assistant/src/activity-3/script.js
  Building_a_Decoupled_Voice_Assistant/src/activity-3/style.css
  Building_a_Decoupled_Voice_Assistant/src/activity-4/fetch.js
  Building_a_Decoupled_Voice_Assistant/src/activity-4/functions/colour.js
  Building_a_Decoupled_Voice_Assistant/src/activity-4/functions/microbytes.js
  Building_a_Decoupled_Voice_Assistant/src/activity-4/index.html
  Building_a_Decoupled_Voice_Assistant/src/activity-4/netlify.toml
  Building_a_Decoupled_Voice_Assistant/src/activity-4/script.js
  Building_a_Decoupled_Voice_Assistant/src/activity-4/style.css
  Building_a_Decoupled_Voice_Assistant/src/activity-5/SHOWCASE.md
Labels: hactoberfest-accepted

#7 Added all files related to micro-byte
  Cross-Platform App in Python/.gitignore
  Cross-Platform App in Python/README.md
  Cross-Platform App in Python/images/preview.gif
  Cross-Platform App in Python/src/app.py
Labels: hactoberfest-accepted

#25 Linear Regression with Regularization
  Linear Regression with Regularization/README.md
  Linear Regression with Regularization/data/data_cleaned.csv
  Linear Regression with Regularization/src/Activity 1/Activity 1 - Understanding Linear Regression.ipynb
  Linear Regression with Regularization/src/Activity 2/Activity 2 - Assumptions of Linear Regression.ipynb
  Linear Regression with Regularization/src/Activity 3/Activity 3 - Ridge, Lasso and ElasticNet Regression.ipynb
Labels: enhancement, good first issue, hacktoberfest-accepted

#45 Hadoop Cluster
  Hadoop Cluster/Images/Activites/Activity 1/Activity 1_Task.png
  Hadoop Cluster/Images/Activites/Activity 1/Activity 1a.png
  Hadoop Cluster/Images/Activites/Activity 1/Activity 1b.png
  Hadoop Cluster/Images/Activites/Activity 1/Activity 1c.png
  Hadoop Cluster/Images/Activites/Activity 2/Activity 2a.png
  Hadoop Cluster/Images/Activites/Activity 2/Activity 2b.png
  Hadoop Cluster/Images/Activites/Activity 3/Activity 3a.png
  Hadoop Cluster/Images/Activites/Activity 3/Activity 3b.png
  Hadoop Cluster/Images/Activites/Activity 3/Activity 3c.png
  Hadoop Cluster/Images/Activites/Activity 3/Activity 3d.png
  Hadoop Cluster/Images/Activites/Activity 7/Activity 7a.png
  Hadoop Cluster/Images/Prerequisites/hadoop_install.png
  Hadoop Cluster/Images/Prerequisites/jdk_install.png
  Hadoop Cluster/Images/dfsadmin.png
  Hadoop Cluster/Images/webui.png
  Hadoop Cluster/README.md
  Hadoop Cluster/src/Clientnode/core-site.xml
  Hadoop Cluster/src/Datanode/core-site.xml
  Hadoop Cluster/src/Datanode/hdfs-site.xml
  Hadoop Cluster/src/Namenode/core-site.xml
  Hadoop Cluster/src/Namenode/hdfs-site.xml
Labels: hacktoberfest-accepted

#46 added a new microbyte for understanding Interfaces in Java
  Interfaces_in_Java/README.md
  Interfaces_in_Java/images/Activity1_output.png
  Interfaces_in_Java/images/Activity3_output.png
  Interfaces_in_Java/images/Bonus_activity_inheritance_hierarchy.png
  Interfaces_in_Java/images/Thumbs.db
  Interfaces_in_Java/images/cardboard-box-types.jpg
  Interfaces_in_Java/images/corrugated-cardboard-sheet.jpg
  Interfaces_in_Java/src/Activity 1/Area.java
  Interfaces_in_Java/src/Activity 1/RectangleArea.java
  Interfaces_in_Java/src/Activity 2/BasePrice.java
  Interfaces_in_Java/src/Activity 3/MainClass.java
  Interfaces_in_Java/src/Activity 3/SellerA.java
  Interfaces_in_Java/src/Activity 3/SellerB.java
Labels: good first issue, hacktoberfest-accepted

#95 Add MicroByte: Learn Building Blocks of Image Processing
  Learn Building Blocks of Image Processing/README.md
  Learn Building Blocks of Image Processing/images/activity-1.png
  Learn Building Blocks of Image Processing/images/activity-2.png
  Learn Building Blocks of Image Processing/images/activity-4.png
  Learn Building Blocks of Image Processing/images/edge.png
  Learn Building Blocks of Image Processing/images/kernel.jpg
  Learn Building Blocks of Image Processing/src/python/Activity (1).py
  Learn Building Blocks of Image Processing/src/python/Activity (2).py
  Learn Building Blocks of Image Processing/src/python/Activity (3).py
  Learn Building Blocks of Image Processing/src/python/Activity (4).py
  Learn Building Blocks of Image Processing/src/python/Activity (5).py
  Learn Building Blocks of Image Processing/src/python/Pipfile
  Learn Building Blocks of Image Processing/src/python/Pipfile.lock
  Learn Building Blocks of Image Processing/src/python/requirements.txt
  Learn Building Blocks of Image Processing/src/python/source.png
  Pipfile
  Pipfile.lock
Labels: hacktoberfest-accepted
